### ISSUE TITLE
Abort doesn't work on Windows

### ISSUE THREAD

**Issue by fabianbehrendt** [samuelcarreira/electron-shutdown-command#1]
When I'm logging `process.platform` it results in `win32`, but I'm still unable to run your _abort_-function.
The solution would be to change the condition of the first if-statement at the _abort_-function at line 101

from

`process.platform !== 'win32' || process.platform !== 'linux'`

to

`process.platform !== 'win32' && process.platform !== 'linux'`

**Comment by samuelcarreira** [comment]
Hi fabianbehrendt, thank you for the correction. I forgot to change the ´´´´if´´´´ clause when I added the support for Linux platform.
It's already fixed on 0.0.7 :-)

**Comment by fabianbehrendt** [comment]
Hey @samuelcarreira, thank you for fixing it that fast. Keep at it and thank you for providing that module!
