### ISSUE TITLE
sudo: effective uid is not 0, is /usr/bin/sudo on a file system with the 'nosuid' option set or an NFS file system without root privileges?

### ISSUE THREAD

**Issue by deanturner** [samuelcarreira/electron-shutdown-command#4]
I am getting this error when I run shutdown from linux
![image](https://user-images.githubusercontent.com/46884043/67016565-03647300-f116-11e9-8157-421cc6b03c02.png)

see above image for more information
please help me 
Thanks

**Comment by samuelcarreira** [comment]
You need to run with root privileges. The `shutdown` on Linux command only works if you run as sudo

**Comment by samuelcarreira** [comment]
https://github.com/samuelcarreira/electron-shutdown-command/issues/3
