### ISSUE TITLE
Windows shutdown not working 

### ISSUE THREAD

**Issue by David-Kopczynski** [samuelcarreira/electron-shutdown-command#5]
I don't know if this project is still maintained, but I am going to ask my question anyways.
When starting the project with npm or yarn I am able to use every single command you offer. However, when packaged something seems odd. Every shutdown I tried just creates a new instance of the application. Some kind of security is in my way, created both by electron-packager oder electron-builder. Even calling a batch or c++ executable doesn't seem to change the problem. 
I am running the newest version of electron and the packagers on windows 10.

**Comment by samuelcarreira** [comment]
Hi there, I have great news. Due to the interest on this simple module, I've decided to completely rewrite it in TypeScript
Please wait a few days for an update.
