### ISSUE TITLE
Nested arrays of arguments intended?

### ISSUE THREAD

**Issue by cuddeford** [samuelcarreira/electron-shutdown-command#6]
`setTimer` returns an array of arguments which is then pushed into the arguments in the enclosing command's function. This produces an array of arguments like so: `['shutdown', ['-t 0']]`. In this implementation there is only one argument added in the `setTimer` function but if there were more than one it would result in a comma added between the arguments.

The code in it's current form throws an error when evaluated by TypeScript.

**Comment by samuelcarreira** [comment]
Hi there, I have great news. Due to the interest on this simple module, I've decided to completely rewrite it in TypeScript
Please wait a few days for an update.
