### ISSUE TITLE
reboot needs options

### ISSUE THREAD

**Issue by brunobg** [samuelcarreira/electron-shutdown-command#8]
I get a `TypeError: Cannot read property 'sudo' of undefined` on index.js:118. This is caused by calling `reboot()` without an argument on Linux. I suggest to provide a default `{}` value for the argument to avoid this.

**Comment by samuelcarreira** [comment]
Hi @brunobg thank you for your input. Did you mean something like that:
`export function reboot(options: ElectronShutdownCommandUserOptions = {})`
?

**Comment by brunobg** [comment]
Exactly that.

**Comment by brunobg** [comment]
I saw your commit. It seems to fix it perfectly. I'm closing this issue. Thanks!
